/*
 * generated by Xtext 2.25.0
 */
package gameoflife


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GofDSLStandaloneSetup extends GofDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new GofDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
